# client/config.py
DEFAULT_SERVER_HOST = "10.100.3.203"
DEFAULT_SERVER_PORT = 5000
RECONNECT_DELAY_INITIAL = 5
RECONNECT_DELAY_MAX = 30
SOCKET_TIMEOUT = 5.0
CONNECTION_RETRY_COUNT = 3
SCREENSHOT_MAX_SIZE = 1024
SCREENSHOT_QUALITY = 75
SCREENSHOT_FORMAT = "JPEG"
UPDATE_INTERVAL = 0.5
PING_INTERVAL = 3.0
PROCESS_SCAN_INTERVAL = 2.0
LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s - %(levelname)s - %(message)s"
LOG_FILE = "client.log"
LOG_DIR = "logs"
MAX_LOG_SIZE = 5 * 1024 * 1024
BACKUP_COUNT = 3
BUFFER_SIZE = 8192
MAX_IMAGE_SIZE = 10 * 1024 * 1024
WEBCAM_MAX_SIZE = 640  # Tamanho máximo (largura/altura) para redimensionamento
WEBCAM_QUALITY = 50    # Qualidade JPEG (0-100)
WEBCAM_FORMAT = "JPEG" # Formato da imagem (JPEG, PNG)
WEBCAM_STREAM_INTERVAL = 0.1  # Intervalo entre frames em segundos
SCREEN_STREAM_MAX_SIZE = 1280  # Tamanho máximo (largura/altura) para redimensionamento
SCREEN_STREAM_QUALITY = 50     # Qualidade JPEG (0-100)
SCREEN_STREAM_FORMAT = "JPEG"  # Formato da imagem (JPEG, PNG)
SCREEN_STREAM_INTERVAL = 0.1   # Intervalo entre frames em segundos
